config/routes.rb
InterviewTool::Application.routes.draw do

'coduru.com'.tap do |host|
    constraints(:host => host) do
      root :to => redirect {|params, req| URI.escape(req.query_string.present? ? "#{req.protocol}www.#{host}?#{req.query_string}" : "#{req.protocol}www.#{host}") }
      match '/*path', :to => redirect {|params, req| URI.escape(req.query_string.present? ? "#{req.protocol}www.#{host}/#{params[:path]}?#{req.query_string}" : "#{req.protocol}www.#{host}/#{params[:path]}") }
    end
end

  resources :interviewers,  :only => [:create, :show, :edit, :destroy, :update]

  resources :interviews, :only => [:create, :show, :destroy, :index]
  resources :sessions,      :only => [:create, :destroy]

  resources :questions, :only => [:create, :destroy, :index]

  match '/interviews/save', :to => 'interviews#save'
  match '/account_settings',      :to => 'interviewers#edit'
  match '/signout',       :to => 'sessions#destroy'
  match '/chat',          :to => 'chat#chat'
  match '/interviews/execute', :to => 'interviews#execute'
  match '/interviews/receive_results', :to => 'interviews#receive_results'
  match '/interviews/change', :to => 'interviews#change'

  root :to => 'pages#home'

  
end

app/models/question.rb
# == Schema Information
#
# Table name: questions
#
#  id             :integer         not null, primary key
#  interviewer_id :integer
#  question       :string(255)
#  codedoc        :string(255)
#  created_at     :datetime        not null
#  updated_at     :datetime        not null
#

class Question < ActiveRecord::Base
  belongs_to :interviewer
  has_and_belongs_to_many :interviews
  has_many :answers

  validates :question,       :presence => true,
                             :length   => { :maximum => 140 }

  validates :interviewer_id, :presence => true
  attr_accessible :question, :interviewer_id, :codedoc
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  # GET /questions
  # GET /questions.json
  def index
    if signed_in?
      @questions = current_user.questions
      @question = Question.new
      respond_to do |format|
        format.html # index.html.erb
        format.json { render :json => @questions }
      end
    else
      redirect_to "/"
    end
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @question = record_error_redir { Question.find(params[:id]) }

    if authenticate_id(@question.interviewer_id)
      respond_to do |format|
        format.html # show.html.erb
        format.json { render :json => @question }
      end
    end
  end

  # GET /questions/new
  # GET /questions/new.json
  def new
    if signed_in?
      @question = Question.new

      respond_to do |format|
        format.html # new.html.erb
        format.json { render :json => @question }
      end
    else
      redirect_to "/"
    end
  end

  # GET /questions/1/edit
  def edit
    @question = record_error_redir { Question.find(params[:id]) }

    authenticate_id(@question.interviewer_id)
  end

  # POST /questions
  # POST /questions.json
  def create
    puts params
    if signed_in?
      @question = Question.new(
                               :interviewer_id => current_user.id,
                               :question => params[:question_question],
                               :codedoc => params[:question_codedoc]
                              )

      respond_to do |format|
        if @question.save
          @text = @question.question
        end
        format.js
      end
    end
  end

  # PUT /questions/1
  # PUT /questions/1.json
  def update
    @question = record_error_redir { Question.find(params[:id]) }

    if (signed_in? and current_user.id == @question.interviewer_id)
      respond_to do |format|
        if @question.update_attributes(params[:question])
          format.html { redirect_to @question, :notice => 'Question was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render :action => "edit" }
          format.json { render :json => @question.errors, :status => :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question = record_error_redir { Question.find(params[:id]) }

    if signed_in? and current_user.id == @question.interviewer_id
      @question.destroy

      respond_to do |format|
        format.html { redirect_to questions_url }
        format.json { head :no_content }
      end
    end
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<% content_for :head do %>
  <script src="<%= s_js_path %>/lib/ace/ace.js" type="text/javascript" charset="utf-8"></script>
  <script src="<%= s_js_path %>/lib/ace/mode-c_cpp.js"></script>
  <script src="<%= s_js_path %>/lib/ace/mode-java.js"></script>
  <script src="<%= s_js_path %>/lib/ace/mode-python.js"></script>
  <script src="<%= s_js_path %>/lib/ace/theme-textmate.js"></script>
  <script src="<%= s_js_path %>/channel/bcsocket.js" type="text/javascript" charset="utf-8"></script>
  <script src="<%= s_js_path %>/share/share.uncompressed.js" type="text/javascript" charset="utf-8"></script>
  <script src="<%= s_js_path %>/share/ace.js" type="text/javascript" charset="utf-8"></script>

  <script type="text/javascript">
    function prepForAce() {
      $("#question_codedoc").hide();
      $("#question_form").submit(
        function() {
          $("#question_codedoc").val(gEditors["editor"].getSession().getValue());
        }
      );
    }

    var supressQuestionSubmit = false;
    $(function() {
      prepForAce();
      $("#question_form").keypress(function(event) {
        if (supressQuestionSubmit) {
          event = event || window.event;
          if (event.keyCode == 13 || event.which == 13) {
            e.preventDefault();
          }
        }
      });

      $("#question_form").bind('ajax:beforeSend', function() {
        supressQuestionSubmit = true;
        $("#save_question").attr("disabled", "disabled");
        $("#question_submit_feedback").html('<%= image_tag('loading.gif') %>');
      });
    });
  </script>
<% end %>

<%= form_tag "/questions", :remote => true, :id => "question_form" do %>
  <div class="field">
    <%= label_tag :question %>
    <%= text_field_tag :question_question, "", :class => "errorable" %>
  </div>
  <div class="field">
    <%= label_tag "Write some template code for your interviewee to use" %>
    <div class="question-editor" id="editor"></div>
    <%= text_area_tag :question_codedoc, "", :class => "errorable" %>
  </div>
  <div class="actions question-actions">
    <%= submit_tag "Save Question", :class => "btn btn-primary", :id => "save_question" %>
    <span id="question_submit_feedback"></span>
  </div>
  <div class="error-space" id="question-error-message"><br /><br /></div>
<% end %>

app/views/questions/create.js.erb
$("#save_question").removeAttr('disabled');

<% if @question.errors.any? %>
  resetQuestionErrors();
  
  $("#question_submit_feedback").html('<%= image_tag('failure.png') %>');

  <% errors = @question.errors %>
  <% attribute = errors.keys()[0] %>
  <% error = errors.full_message(attribute, errors.get(attribute)[0]) %>

  setQuestionErrors("<%= attribute %>", "<%= error %>");

  if (typeof question_not_saved  == 'function') {
    question_not_saved();
  }

<% else %>
  resetQuestionErrors();
  $("#question_submit_feedback").html('<%= image_tag("success.png") %>');
  var question = "<%= @text %>";
  // This will straight up error in the modal case...
  // Fortunately the user will never know!
  if ($("#questions").length) {
    $("#questions").append('<tr><td>' + question + '</td><td>None</td></tr>').find('tr:last').hide().fadeIn('slow');
  }

  // Clear the fields
  $("#question_question").val('');
  $("#question_codedoc").val('');

  // Will only run if you are rendering this form outside
  // of the normal parameters, like in a modal because question_saved is
  // only defined in that html.
  if (typeof question_saved  == 'function') {
    var question_data = {};
    question_data["id"] = <%= @question.id  %>;
    question_data["question"] = "<%= escape_javascript(@question.question) %>";
    question_data["codedoc"] = "<%= escape_javascript(@question.codedoc) %>";
    question_saved(question_data);
    $(".errorable").blur();
  }

<% end %>
supressQuestionSubmit = false;

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<% content_for :head do %>
  <script type="text/javascript">
    $(function() {
      setUpAce("editor");
    });
  </script>
<% end %>

<h1>My Questions</h1>
<div class="row">
<div class="questions-listing span8">
<table id="questions" class="table table-striped">
  <tr>
    <th>Question</th>
    <th>Answers</th>
  </tr>

  <% @questions.each do |question| %>
    <tr>
      <td><%= question.question %></td>
      <td><% if question.answers.length == 0 %>
        None   
        <% else %>
        <%= question.answers.length %>
        <% end %>
      </td>
  </tr>
<% end %>
</table>
</div>
<div class="new question span4">
<h2>Create Question</h2>
<%= render "form" %>
</div>

</div>

app/views/questions/new.html.erb
<h1>New question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Interviewer:</b>
  <%= @question.interviewer_id %>
</p>

<p>
  <b>Question:</b>
  <%= @question.question %>
</p>

<p>
  <b>Codedoc:</b>
  <%= @question.codedoc %>
</p>