config/routes.rb
InterviewTool::Application.routes.draw do

'coduru.com'.tap do |host|
    constraints(:host => host) do
      root :to => redirect {|params, req| URI.escape(req.query_string.present? ? "#{req.protocol}www.#{host}?#{req.query_string}" : "#{req.protocol}www.#{host}") }
      match '/*path', :to => redirect {|params, req| URI.escape(req.query_string.present? ? "#{req.protocol}www.#{host}/#{params[:path]}?#{req.query_string}" : "#{req.protocol}www.#{host}/#{params[:path]}") }
    end
end

  resources :interviewers,  :only => [:create, :show, :edit, :destroy, :update]

  resources :interviews, :only => [:create, :show, :destroy, :index]
  resources :sessions,      :only => [:create, :destroy]

  resources :questions, :only => [:create, :destroy, :index]

  match '/interviews/save', :to => 'interviews#save'
  match '/account_settings',      :to => 'interviewers#edit'
  match '/signout',       :to => 'sessions#destroy'
  match '/chat',          :to => 'chat#chat'
  match '/interviews/execute', :to => 'interviews#execute'
  match '/interviews/receive_results', :to => 'interviews#receive_results'
  match '/interviews/change', :to => 'interviews#change'

  root :to => 'pages#home'

  
end

app/controllers/interviews_controller.rb
class InterviewsController < ApplicationController
  helper_method :api_key
  helper_method :token

  require 'net/http'
  require 'uri'
  require 'juggernaut'
  require 'opentok'

  # GET /interviews
  # GET /interviews.json
  def index
    if authenticate
      @interviews = current_user.interviews
      @interview = Interview.new
      @interviewee = Interviewee.new

      respond_to do |format|
        format.html # index.html.erb
        format.json { render :json => @interviews }
      end
    end
  end

  # GET /interviews/1
  # GET /interviews/1.json
  def show
    @interview = record_error_redir { Interview.find(params[:id]) }
    interviewer = @interview.interviewer
    @is_interviewer = signed_in? && current_user?(interviewer)

    user = nil
    if @is_interviewer
      user = interviewer
    elsif params[:key] == @interview.key
      user = @interview.interviewee
    else
      deny_access
      return
    end

    @name = user.name
    @curr_answer_id = 0
    @curr_answer_text = ""
    @curr_answer_lang = "none"
    @curr_question = ""
    @questions_tags = []

    answers = @interview.answers
    if !answers.empty?
      @questions_tags = @interview.answers.collect do |answer|
        [answer.question.question, answer.id]
      end

      curr_answer = Answer.find(@interview.current_answer)
      @curr_question = curr_answer.question.question
      @curr_answer_id = curr_answer.id
      @curr_answer_text = curr_answer.answer
      @curr_answer_lang = curr_answer.language
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @interview }
    end
  end

  # GET /interviews/new
  # GET /interviews/new.json
  def new
    if authenticate
      @interview = Interview.new
      @interviewee = Interviewee.new

      respond_to do |format|
        format.html # new.html.erb
        format.json { render :json => @interview }
      end
    end
  end

  # GET /interviews/1/edit
  def edit
    @interview = record_error_redir { Interview.find(params[:id]) }

    if authenticate_id(@interview.id)
      @interviewee = @interview.interviewee
    end
  end

  # POST /interviews
  # POST /interviews.json
  def create
    if signed_in?
      @interviewee = Interviewee.new(params[:interviewee])
      #new_min = params[:interview]["time_start(5i)"].to_i - (current_user.timezone - params[:dst].to_i)
      @interview = Interview.new(params[:interview])
      puts params
      @interview.interviewer_id = current_user.id
      @interview.rating = 0

      check = @interview.valid?
      check2 = @interviewee.valid?
      @valid = check && check2

      if @valid
        @interviewee.save

        # Generate a random key
        o =  [('a'..'z'),('A'..'Z'),('0'...'9')].map{|i| i.to_a}.flatten
        @interview.key = (0...16).map{o[rand(o.length)]}.join

        @interview.interviewee = @interviewee
        if !params[:interview_questions].nil?
          params[:interview_questions].each do |n|
            question = Question.find(n)
            question.interviews << @interview
            answer = Answer.new(:answer => question.codedoc, :language => "none")
            question.answers << answer
            @interview.answers << answer

            answer.save
          end

          @interview.current_answer = @interview.answers[0].id
        end

        # TOKBOX
        config_opentok
        session_properties = {OpenTok::SessionPropertyConstants::P2P_PREFERENCE => "enabled"}
        session = @opentok.create_session request.remote_addr, session_properties
        @interview.session_id = session.session_id
        #token = @opentok.generate_token :session_id => @session
        # end TokBox stuff

        @interview.save

        Thread.new do
          InterviewMailer.invite_interviewee(@interview).deliver
        end
      end

      respond_to do |format|
        format.js
      end
    end
  end

  # PUT /interviews/1
  # PUT /interviews/1.json
  def update
    @interview = record_error_redir { Interview.find(params[:id]) }

    if (signed_in? and @interview.interviewer_id == current_user.id)
      respond_to do |format|
        if @interview.update_attributes(params[:interview])

          if !params[:questions].nil?
            params[:questions].each do |n|
              question = Question.find(n)
              question.interviews << @interview
              @interview.questions << question
            end
          end
          @interview.save

          format.html { redirect_to @interview, :notice => 'Interview was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render :action => "edit" }
          format.json { render :json => @interview.errors, :status => :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /interviews/1
  # DELETE /interviews/1.json
  def destroy
    @interview = record_error_redir { Interview.find(params[:id]) }

    if (signed_in? and @interview.interviewer_id == current_user.id)
      @interview.interviewee.destroy
      @interview.answers.each do |answer|
        answer.destroy
      end

      @interview = Interview.find(params[:id])
      @interview.destroy

      respond_to do |format|
        format.html { redirect_to interviews_url }
        format.json { head :no_content }
      end
    end
  end

  # POST /interviews/save
  def save
    if params.has_key?(:interview_id)
      interview = record_error_redir { Interview.find(params[:interview_id]) }

      if !(signed_in? and interview.interviewer_id == current_user.id)
        return
      end

      if params.has_key?(:notes)
        interview.notes = params[:notes]
      end

      if params.has_key?(:curr_answer)
        interview.current_answer = params[:curr_answer]
      end

      interview.save
    end

    if params.has_key?(:answer_id)
      answer = record_error_redir { Answer.find(params[:answer_id]) }

      if !(signed_in? and answer.interview.interviewer_id == current_user.id)
        return
      end

      if params.has_key?(:answer)
        answer.answer = params[:answer]
      end

      if params.has_key?(:language)
        key = answer.interview.key
        Juggernaut.publish("/lang_#{key}", {:language => params[:language]})
        answer.language = params[:language]
      end

      answer.save
    end

    render :nothing => true
  end



  # POST /interviews/execute
  def execute
    post_uri = URI('http://10.252.14.246:8000/exec/899190/')
    begin
      response = Net::HTTP.post_form(post_uri, { :language => params[:lang], :code => params[:code], :room => params[:key] })
    rescue
      Juggernaut.publish("/code_#{params[:key]}", "Error executing code...\nPlease try again later.")
    end

    render :nothing => true
  end

  def receive_results
    if request.env['REMOTE_ADDR'] == '10.252.14.246'
      Juggernaut.publish("/code_#{params[:key]}", params[:output])

      render :nothing => true
    end
  end

  def change
    @answer = record_error_redir { Answer.find(params[:answer]) }
    interview = @answer.interview

    if (signed_in? and current_user.id == interview.interviewer_id)
      interview.current_answer = params[:answer]

      interview.save
      Juggernaut.publish("/answers_#{@answer.interview.key}", {:id => @answer.id, :code => @answer.answer, :question => @answer.question.question})

      respond_to do |format|
        format.js # change.js.erb
      end
    end
  end

  # Used to create a TokBox session.
  # api_key and token are shared with the view.
  private
  def api_key
    @api_key = 14618952
  end

  def api_secret
    @api_secret = "85f96b93e3a07a4f0af20a890612a3ea602fbba1"
  end

  def config_opentok
    if @opentok.nil?
      @opentok = OpenTok::OpenTokSDK.new api_key, api_secret
    end
  end

  def token(id)
    config_opentok
    @token = @opentok.generate_token :session_id => id
  end
end

app/helpers/interviews_helper.rb
module InterviewsHelper
  Error = Struct.new(:attribute, :error)

  def supported_lang_options
    return [["None", "none"], ["C", "c"], ["C++", "c++"], ["Java", "java"], ["Python", "python2"]]
  end

  def get_questions
    questions = current_user.questions.collect do |question|
      [question.question, question.id]
    end
  end

  def get_chat_html(chat)
    if chat.nil?
      return ''
    end

    chat_html = ""
    chat.split('\n').each do |line|
      (name, chat) = line.split('\t')
      chat_html = chat_html + '<b>' + name + ': </b>' + chat + '<br>'
    end

    return raw(chat_html)
  end

  def upcoming_interviews()
    return current_user.interviews.where("time_start >= :now", { :now => Time.now}).order("time_start ASC")
  end

  def previous_interviews(amount = -1)
    old_interviews = current_user.interviews.where("time_start < :now", { :now => Time.now}).order("time_start DESC")
    return old_interviews
  end

  def get_error_info(interviewee, interview)
    errors = interviewee.errors
    if errors.empty?
      errors = @interview.errors
    end
    attribute = errors.keys()[0]
    error = errors.full_message(attribute, errors.get(attribute)[0])

    e = Error.new
    e.attribute = attribute
    e.error = error

    return e

  end
end

app/views/interviews/_chat_and_video.html.erb
<% content_for :head do %>
<script type= "text/javascript">
    $(function() {
        scroll_to_end_of_chat();

        // Set up
        var jug = new Juggernaut;
        jug.subscribe(<%= %Q('/chat_#{@interview.key}')  %>, function(data) {
            handleChat(data);
        });

        $("#chat_form").bind("ajax:beforeSend", function() {
            $("#chat_text").val('');
        });
    });
</script>
<% end %>

<div class="span3 ivu-chat" id="chat_container">
    <div class="row-fluid" id="video_container">
        <div class="row-fluid subscriber_container">
            <img src="<%= image_path("novideo.png") %>" id="novideo_image1" alt="No Video" />
        </div>
        <div class="row-fluid" id="my_video_and_buttons">
            <div class="row-fluid my_video_container">
                <img src="<%= image_path("novideo.png") %>" id="novideo_image2" alt="No Video" />
            </div>
            <div class="row-fluid" id="video_buttons">
                <div id='buttons_loading'></div>
            </div>
        </div>
    </div>
    <div id="chat_hist">
        <%= get_chat_html(@interview.chat) %>
    </div>
    <div class="chat_submit">
        <%= form_tag "/chat", :remote => true, :id => "chat_form" do %>
        <%= text_field_tag :chat_text, nil, :autocomplete => :off %>
        <%= hidden_field_tag :id, @interview.id %>
        <%= hidden_field_tag :name, @name %>
        <%= submit_tag "Send chat", :class => "btn btn-primary", :id => "send_chat" %>
        <% end %>
    </div>
</div>

app/views/interviews/_code.html.erb
<div class="row-fluid">
    <div class="current-question">
        <%= @curr_question %>
    </div>
    <% if @is_interviewer %>
        <div class="interview_box_interviewer" id="editor"></div>
    <% else %>
        <div class="interview_box_interviewee" id="editor"></div>
    <% end %>
</div>
<% if @is_interviewer %>
    <div class="row-fluid">
        <%= text_area_tag(:notes, @interview.notes, :placeholder => "Notes...", :size => "500x100") %>
    </div>
<% end %>

app/views/interviews/_edit_form.html.erb
<%= form_for(@interview) do |f| %>
  <% if @interview.errors.any? or @interviewee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@interview.errors.count + @interviewee.errors.count, "error") %> prohibited this interview from being saved:</h2>

      <ul>
      <% @interviewee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      <% @interview.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= label_tag :email, "Interviewee's Email" %><br />
    <%= @interviewee.email %>
  </div>
  <div class="field">
    <%= f.label :time_start %><br />
    <%= f.datetime_select :time_start %>
  </div>
  <div class="field">
    <%= label_tag "Questions" %><br />
    <% questions = current_user.questions.collect do |question|
         [question.question, question.id]
       end %>
    <%= select_tag :questions, options_for_select(questions), {:multiple => true, :size => 5} %>
  </div>
  <div class="field">
    <input type="hidden" id="dst" name="dst" value="" />
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/interviews/_interviewee_show.html.erb
<% content_for :head do %>
<script type="text/javascript">
  $(function() {
    var jugAnswer = new Juggernaut;
    jugAnswer.subscribe(<%= %Q('/answers_#{@interview.key}') %>, function(data) {
      changeQuestion(data);
//      $(".current-question").text(data["question"]);
//      $("#answer_id").val(data["id"]);
    });

    var jugLang = new Juggernaut;
    jugLang.subscribe(<%= %Q('/lang_#{@interview.key}') %>, function(data) {
      // Updates syntax highlighting when language changes
      set_syntax_lang(data["language"]);
    });

    $(window).unload(disconnect);
  });
</script>
<% end %>

<div class="interview_room">
  <h1>Interview Room</h1>
  <%= hidden_field_tag(:answer_id, @curr_answer_id) %>
  <div class="row-fluid">
    <div class="span9 ivu-code">
      <%= render 'code' %>
      <div class="row-fluid" id="console_interviewee">
	<br/>
	Console:
        <%= text_area_tag(:console, "", :readonly => :readonly) %>
      </div>
    </div>
    <%= render 'chat_and_video' %>
  </div>
</div>

app/views/interviews/_interviewer_show.html.erb
<% content_for :head do %> 
<script type="text/javascript">
  function setUpJugg() {
    var jug_quest = new Juggernaut;
    jug_quest.subscribe(<%= %Q('/answers_#{@interview.key}') %>, function(data) {
      changeQuestion(data);
      if ("id" in data) {
        gEditors["editor"].getSession().setValue(data["code"]);
      }
    });
  }

  $(function() {
    setUpJugg();

    // Events
    gEditors["editor"].getSession().on('change', function() { onEditorChange() });
    $(window).unload(function() { onUnload(<%= @interview.id %>); });
    $("#languages").change(function() { onLangChange() });
    $("#code_exec").click(function() { onExecuteCode(<%= %Q('#{@interview.key}') %>) });
    $("#notes").keyup(function() { onNotesChanged(<%= @interview.id %>) });
  });
</script>
<% end %>

<div class="interview_room">
  <h1>Interview Room</h1>
  <%= hidden_field_tag(:answer_id, @curr_answer_id) %>
  <div class="row-fluid">
    <div class="span3 ivu-questions">
      <div class="row-fluid" id="questions_and_buttons">
        <%= select_tag(:languages, options_for_select(supported_lang_options, @curr_answer_lang)) %>
        <%= form_tag("/interviews/change", :method => "post", :remote => "true") do %>
          <%= select_tag(:answer, options_for_select(@questions_tags, @curr_answer_id), {:size => 15}) %>
          <div class="ivu-lbuttons">
            <%= submit_tag("Change question", {:class => "btn btn-primary"} ) %>
            <% if @curr_answer_lang == "none" %>
              <input type="button" id="code_exec" value="Execute code!" disabled="disabled" class="btn btn-danger"/>
            <% else %>
              <input type="button" id="code_exec" value="Execute code!" class="btn btn-danger"/>
            <% end %>
          </div>
        <% end %>
      </div>
      <div class="row-fluid" id="console_interviewer">
	    <%= text_area_tag(:console, "", :readonly => :readonly) %>
      </div>
    </div>
    <div class="span6 ivu-code">
      <%= render 'code' %>
    </div>
    <%= render 'chat_and_video' %>
  </div>
</div>

app/views/interviews/_new_form.html.erb
<% content_for :head do %>
<script type="text/javascript">
function openModal() {
  $("#new-question").modal('show');
}


function question_saved(question_data) {
  $("#new-question").modal('hide');
  $("#interview_questions").append("<option value=" + question_data["id"] + " selected='selected'>" + question_data["question"] + "</option>");
  var numQuestions = $("#interview_questions option").size();
  var sizeQuestions = $("#interview_questions").attr("size");
  var scrollHeight = $("#interview_questions").prop("scrollHeight") * (numQuestions - sizeQuestions + 1) / numQuestions;
  $("#interview_questions").scrollTop(scrollHeight);
  $("#submit_feedback").html('');
}

function reset_modal() {
  resetQuestionErrors();
  $("#submit_feedback").html('');
  closeAce("editor");
}

var supressInterviewSubmit = false;
$(function(){
  $("#new_interview").keypress(function(event) {
    if (supressInterviewSubmit) {
      event = event|| window.event;
      if (event.keyCode == 13 || event.which == 13) {
        e.preventDefault();
      }
    }
  });

  $("#new-question").modal({show: false});
  $("#new-question").on('shown',
    function () {
      setUpAce("editor");      
    }
  );

  $('.datepick').datetimepicker({
      dateFormat: "MM dd, yy",
      stepMinute: 5,
      stepHour: 1
  });

  $("#new_interview").bind('ajax:beforeSend', function () {
    supressInterviewSubmit = true;
    $("#save_interview").attr("disabled", "disabled");
    $("#int_submit_feedback").html('<%= image_tag("loading.gif") %>');
  });

  $("#make-ques-button").click(function () {
    openModal();
  });

  $("#new-question").on('hidden', function() {
    reset_modal();
  });

});
</script>
<% end %>

<%= form_for @interview, :remote => true, :disable_with => "Submitting..." do |f| %>
  <div class="field">
    <%= label_tag :name, "Name of interviewee" %>
    <%= text_field :interviewee, :name, :class => "errorable" %>
  </div> 
  <div class="field">
    <%= label_tag :email, "Their email" %>
    <%= text_field :interviewee, :email, :class => "errorable" %>
  </div>
  <div class="field">
    <%= f.label :time, "Day and Time - #{current_user.time_zone}" %>
    <%= f.text_field :time_start, {:class => "datepick errorable"}  %>
  </div>
  <div class="field">
    <%= label_tag "Pick some  questions to ask:" %>
    <%= select_tag :interview_questions, options_for_select(get_questions),  {:multiple => true, :size => 5} %>
    <a class="btn btn-success" id="make-ques-button">New question</a>
  </div>
  <div class="actions">
    <br/>
    <%= f.submit "", :class => "btn btn-primary btn-large", :value => "Create Interview", :id => "save_interview" %>
    <span id="int_submit_feedback"></span>
  </div>
  <div class="error-space" id="interview-error-message"><br /><br /></div>
<% end %>

<div class="modal fade hide" id="new-question">
  <div class="modal-header">
    <button class="close" data-dismiss="modal" id="close-modal">X</button>
    <h3>New Question</h3>
  </div>
  <div class="modal-body">
    <%= render "/questions/form" %>
  </div>
</div>

app/views/interviews/change.js.erb
gEditors['editor'].getSession().setValue("<%= raw(@answer.answer) %>");

var lang = <%= %Q('#{@answer.language}') %>;
$("#languages").val(lang);
$(".current-question").text(<%= %Q('#{@answer.question.question}') %>);
$("#answer_id").val(<%= @answer.id %>);

if (lang == "none") {
  $("#code_exec").attr("disabled", "disabled");
} else {
  $("#code_exec").removeAttr("disabled");
}

app/views/interviews/create.js.erb
$("#save_interview").removeAttr('disabled');
<% if @valid %>
  window.location = <%= "'" + interview_path(@interview) + "'" %>;
<% else %>
  $("#int_submit_feedback").html('<%= image_tag("failure.png") %>');

  resetInterviewErrors();

  <% error = get_error_info(@interviewee, @interview) %>
  
  setInterviewErrors("<%= error.attribute %>", "<%= error.error %>");
<% end %>
supressInterviewSubmit = false;

app/views/interviews/edit.html.erb
<h1>Editing interview</h1>

<%= render 'edit_form' %>

<%= link_to 'Show', @interview %> |
<%= link_to 'Back', interviews_path %>

app/views/interviews/index.html.erb
<div class="interviews-page row">
<div class="interview-list span8">
<h2>Upcoming interviews</h2>
<table class="table table-striped">
  <tr>
    <th>Interview date</th>
    <th>With</th>
    <th>Email</th>
  </tr>

<% upcoming_interviews.each do |interview| %>
  <tr>
        <% ivu_interviewee = Interviewee.find(interview.interviewee_id) %>
    <td><%= link_to interview.time_start.to_s(:long), interview  %></td>
    <td><%= ivu_interviewee.name %></td>
    <td><%= mail_to ivu_interviewee.email %></td>
  </tr>
<% end %>
</table>

<br />
<h2>Recent interviews</h2>
<table class="table table-striped">
  <tr>
    <th>Interview date</th>
    <th>With</th>
    <th>Email</th>
  <!--  <th>Performance</th> -->
  </tr>

<% previous_interviews.each do |interview| %>
  <tr>
        <% ivu_interviewee = Interviewee.find(interview.interviewee_id) %>
    <td> <%= link_to interview.time_start.to_s(:long), interview  %></td>
    <td><%= ivu_interviewee.name %></td>
    <td><%= mail_to ivu_interviewee.email %></td>
<!--    <td>
      <input class="star" name="<%= interview.id %>" type="radio" title="Poor" value="1"></input>
      <input class="star" name="<%= interview.id %>" type="radio" title="Below expectations" value="2"></input>
      <input class="star" name="<%= interview.id %>" type="radio" title="Interesting" value="3"></input>
      <input class="star" name="<%= interview.id %>" type="radio" title="Very good" value="4"></input>
      <input class="star" name="<%= interview.id %>" type="radio" title="Must hire" value="5"></input>
    </td> -->
<% end %></tr>
</table>


</div>
<div class="ivulist-new span4">
<h2>Schedule Interview</h2>
<%= render "new_form" %>
</div>

</div>

app/views/interviews/new.html.erb
<h1>New interview</h1>

<%= render 'new_form' %>

<%= link_to 'Back', interviews_path %>

app/views/interviews/show.html.erb
<% content_for :head do %>
  <script src="http://static.opentok.com/v0.91/js/TB.min.js" type="text/javascript" charset="utf-8"></script>
  <script src="<%= s_js_path %>/lib/ace/ace.js" type="text/javascript" charset="utf-8"></script>
  <script src="<%= s_js_path %>/lib/ace/mode-c_cpp.js"></script>
  <script src="<%= s_js_path %>/lib/ace/mode-java.js"></script>
  <script src="<%= s_js_path %>/lib/ace/mode-python.js"></script>
  <script src="<%= s_js_path %>/lib/ace/theme-textmate.js"></script>
  <script src="<%= s_js_path %>/channel/bcsocket.js" type="text/javascript" charset="utf-8"></script>
  <script src="<%= s_js_path %>/share/share.uncompressed.js" type="text/javascript" charset="utf-8"></script>
  <script src="<%= s_js_path %>/share/ace.js" type="text/javascript" charset="utf-8"></script>
  <script src="<%= base_url %>:8080/application.js" type="text/javascript" charset="utf-8"></script>
  <script type="text/javascript">
    // Used to set initial variables
    setInitVars(<%= api_key %>, '<%= @interview.session_id %>', '<%= token(@interview.session_id) %>', '<%= raw(image_tag("loading.gif")) %>');
    
    $(function() {
      setUpAce("editor");
      set_syntax_lang($("#languages").val());

      var docName = "<%= 'code:' + @interview.key %>";
      var initText = "<%= raw(@curr_answer_text) %>";
      var path = '<%= s_js_path %>'

      setUpShareJS("editor", docName, path, initText);

      var jugConsole = new Juggernaut;
      jugConsole.subscribe(<%= %Q('/code_#{@interview.key}') %>, function(data) {
        $("#console").val(data);
      });
    });

  </script>
<% end %>
<%= if @is_interviewer
      render 'interviewer_show'
    else
      render 'interviewee_show'
end %>