config/routes.rb
InterviewTool::Application.routes.draw do

'coduru.com'.tap do |host|
    constraints(:host => host) do
      root :to => redirect {|params, req| URI.escape(req.query_string.present? ? "#{req.protocol}www.#{host}?#{req.query_string}" : "#{req.protocol}www.#{host}") }
      match '/*path', :to => redirect {|params, req| URI.escape(req.query_string.present? ? "#{req.protocol}www.#{host}/#{params[:path]}?#{req.query_string}" : "#{req.protocol}www.#{host}/#{params[:path]}") }
    end
end

  resources :interviewers,  :only => [:create, :show, :edit, :destroy, :update]

  resources :interviews, :only => [:create, :show, :destroy, :index]
  resources :sessions,      :only => [:create, :destroy]

  resources :questions, :only => [:create, :destroy, :index]

  match '/interviews/save', :to => 'interviews#save'
  match '/account_settings',      :to => 'interviewers#edit'
  match '/signout',       :to => 'sessions#destroy'
  match '/chat',          :to => 'chat#chat'
  match '/interviews/execute', :to => 'interviews#execute'
  match '/interviews/receive_results', :to => 'interviews#receive_results'
  match '/interviews/change', :to => 'interviews#change'

  root :to => 'pages#home'

  
end

app/models/interviewer.rb
# == Schema Information
#
# Table name: interviewers
#
#  id                 :integer         not null, primary key
#  email              :string(255)
#  created_at         :datetime        not null
#  updated_at         :datetime        not null
#  salt               :string(255)
#  encrypted_password :string(255)
#  email_verified     :boolean
#  time_zone          :string(255)
#  name               :string(255)
#

require 'digest'

class Interviewer < ActiveRecord::Base
    # Password stored virtually, not written in cleartext to the database
    attr_accessor :password, :updating_password

    # Accessible attributes
    attr_accessible :name, :email, :password, :time_zone

    # Regular expression to verify for a valid email syntax.
    email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

    has_many :interviews
    has_many :questions

    # Verifying fields

    validates :name, :length => { :maximum => 50 },
                     :presence => true

    # ensures email exists, has correct syntax and is unique
    validates :email, :presence => true,
                      :format => { :with => email_regex },
                      :uniqueness => { :case_sensitive => false }

    # Ensures password exists, is within range and has a confirmation attribute
    # if should_validate_password?
        validates :password, :presence       => true,
                             :length         => { :within => 6..40 }, :if => :should_validate_password?

  # validates_presence_of :password if :should_validate_password?

 # Make sure we encrypt and store the password before we write to the database
 # if we are updating the password
    before_save :encrypt_password, :if => :should_validate_password?


  # Returns true if the password is set to be changed or if it's the creation of a user
  def should_validate_password?
    updating_password || new_record?
  end

  # Return true if the submitted password matches the submitted password
  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end

  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil if user.nil?
    return user if user.has_password?(submitted_password)
  end

  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end

  def email_verified?
    email_verified
  end


  private
  def encrypt_password
    self.salt = make_salt unless has_password?(password)
    self.encrypted_password = encrypt(password)
  end

  def encrypt(string)
    secure_hash("#{salt}--#{string}")
  end

  def make_salt
    secure_hash("#{Time.now.utc}--#{password}")
  end

  def secure_hash(string)
    Digest::SHA2.hexdigest(string)
  end
end

app/controllers/interviewers_controller.rb
class InterviewersController < ApplicationController
  # GET /interviewers
  # GET /interviewers.json
  def index
    @interviewers = Interviewer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @interviewers }
    end
  end

  # GET /interviewers/1
  # GET /interviewers/1.json
  def show
    # For now, just redirect to the interviews page
    redirect_to '/interviews'
#    @interviewer = Interviewer.find(params[:id])

#    if authenticate_id(@interviewer.id)
#      respond_to do |format|
#        format.html # show.html.erb
#        format.json { render json: @interviewer }
#      end
#    end
  end

  # GET /interviewers/1/edit
  def edit
    @interviewer = record_error_redir { Interviewer.find(params[:id]) }

    authenticate_id(@interviewer.id)
  end

  # POST /interviewers
  # POST /interviewers.json
  def create
    @interviewer = Interviewer.new(params[:interviewer])

    @saved = @interviewer.save

    if @saved
      # Sign the user in
      sign_in @interviewer
    end

    respond_to do |format|
      format.js
    end
  end

  # PUT /interviewers/1
  # PUT /interviewers/1.json
  def update
    @interviewer = record_error_redir { Interviewer.find(params[:id]) }

    if current_user?(@interviewer)
      if params[:interviewer][:password].blank?
        params[:interviewer].delete(:password)
        params[:interviewer].delete(:password_confirmation)
      end

      respond_to do |format|
        # Check that current password field is matching before doing anything.
        if @interviewer == Interviewer.authenticate(@interviewer.email,
                                                    params[:interviewer][:current_password])
          #params[:interviewer].delete(:current_password)

          #params[:interviewer].delete(:password)
          #params[:interviewer].delete(:password_confirmation)

          # Always update the normal attributes
          @interviewer.name = params[:interviewer][:name]
          @interviewer.email = params[:interviewer][:email]
          @interviewer.time_zone = params[:interviewer][:time_zone]
          # Attempt to update password if the user gave an input.
          if !params[:interviewer][:password].blank?
            @interviewer.updating_password = true
            @interviewer.password = params[:interviewer][:password]
            @interviewer.password_confirmation = params[:interviewer][:password_confirmation]
          end

          # check if the update was successful
          if @interviewer.save
            # signing in interviewer again in case email or password were changed
            sign_in @interviewer
            format.html { render action: "edit", notice: 'Interviewer was successfully updated.' }
            # redirect_to account_settings_path
            format.json { head :no_content }
          else
            format.html { render action: "edit" }
            format.json { render json: @interviewer.errors, status: :unprocessable_entity }
          end
          # If the current password is wrong
        else
          format.html { render action: "edit" }
          format.json { render json: @interviewer.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /interviewers/1
  # DELETE /interviewers/1.json
  def destroy
    @interviewer = record_error_redir { Interviewer.find(params[:id]) }

    if current_user?(@interviewer)
      @interviewer.destroy

      respond_to do |format|
        format.html { redirect_to interviewers_url }
        format.json { head :no_content }
      end
    end
  end
end

app/helpers/interviewers_helper.rb
module InterviewersHelper
  def recent_interviews(interviewer)

  end

  def possible_timezones()
    time_zones = (-720..840).step(15)
    time_zone_names = time_zones.collect do |time|
      ["UTC %+d:%02d" % [time / 60, time.modulo(60)], time]
    end
    return time_zone_names
  end
end

app/views/interviewers/_account_settings.html.erb
<div class="account-page row">

<div class="span12"
<%= form_for(@interviewer) do |f| %>
  <% if @interviewer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@interviewer.errors.count, "error") %> prohibited this interviewer from being saved:</h2>

      <ul>
      <% @interviewer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  
  <div class="field">
   <%= f.label :time_zone%>
   <%= f.time_zone_select(:time_zone, ActiveSupport::TimeZone.us_zones)  %>
  </div>

  <div class="field">
    <%= f.label "Current password" %>
    <p>Required for security purposes</p>
    <%= f.password_field "current_password" %>
  </div>
  <div class="field">
    <%= f.label "New password"%>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
    <div class="actions signup">
    <%= f.submit "", :class => "btn btn-primary", :value => "Submit"  %>
  </div>


<% end %>
</div>
</div>

app/views/interviewers/_form.html.erb
<% content_for :head do %>
  <script type="text/javascript">
    var supressInterviewerSubmit = false;

    $(function() {
      $("#new_interviewer").keypress(function(event) {
        if (supressInterviewerSubmit) {
          event = event|| window.event;
          if (event.keyCode == 13 || event.which == 13) {
            e.preventDefault();
          }
        }
      });

      $("#new_interviewer").bind('ajax:beforeSend', function() {
        supressInterviewerSubmit = true;
        $("#save_interviewer").attr("disabled", "disabled");
        $("#submit_feedback").html('<%= image_tag('loading.gif') %>');
      });
    });
  </script>
<% end %>

<%= form_for @interviewer, :remote => true do |f| %>
  <div class="field">
    <%= f.text_field :name, :class => :errorable, :placeholder=>"Name" %>
  </div>
  <div class="field">
    <%= f.text_field :email, :class => :errorable, :placeholder=>"Email" %>
  </div>
  <div class="field">
    <%= f.time_zone_select :time_zone, ActiveSupport::TimeZone.us_zones, {:default => "Pacific Time (US & Canada)"}, :class => :errorable %>
  </div>
  <div class="field">
    <%= f.password_field :password, :class => :errorable, :placeholder=>"Password" %>
  </div>
  <div class="error-space" id="error-message"><br /></div>
  <%= f.submit "", :class => "btn btn-success btn-large", :value => "Create Account", :id => "save_interviewer" %>
  <span id="submit_feedback"></span>
<% end %>

app/views/interviewers/create.js.erb
$("#save_interviewer").removeAttr('disabled');
<% if @saved %>
  window.location = '<%= interviewer_path(@interviewer) %>';
<% else %>
  resetInterviewerErrors();
  $("#submit_feedback").html('<%= image_tag("failure.png") %>');

  <% errors = @interviewer.errors %>
  <% attribute = errors.keys()[0] %>
  <% error = errors.full_message(attribute, errors.get(attribute)[0]) %>

  setInterviewerErrors("<%= attribute %>", "<%= error %>");
<% end %>
supressInterviewerSubmit = false;

app/views/interviewers/edit.html.erb
<h1>Account settings</h1>
<% if !notice.blank? %>
  <p id="notice"> <%= notice %> </p>
<% end %>
<%= render 'account_settings' %>

app/views/interviewers/index.html.erb
<h1>Listing interviewers</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @interviewers.each do |interviewer| %>
  <tr>
    <td><%= interviewer.first_name %></td>
    <td><%= interviewer.last_name %></td>
    <td><%= interviewer.email %></td>
    <td><%= link_to 'Show', interviewer %></td>
    <td><%= link_to 'Edit', edit_interviewer_path(interviewer) %></td>
    <td><%= link_to 'Destroy', interviewer, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Interviewer', new_interviewer_path %>

app/views/interviewers/new.html.erb
<h1>New interviewer</h1>

<%= render 'form' %>

<%= link_to 'Back', interviewers_path %>

app/views/interviewers/show.html.erb
<% if !notice.blank? %>
  <p id="notice"><%= notice %></p>
<% end %>
<h1><%=@interviewer.name %></h1>

<div class="my-interviews">
  <h2>My Interviews</h2>
  <h3>Upcoming</h3>
  <% if !@interviewer.interviews.blank? %>
  <table class="interview-table">
    <tr class="table-headers">
      <td>With</td>
      <td>Date</td>
      <td>Email</td>
    </tr>
  <% for interview in @interviewer.interviews %>
    <tr > 
      <td><%= link_to interview.interviewee.name, interview %></td>
      <td><%= interview.time_start.to_formatted_s(:long)%></td>
      <td><%= mail_to(interview.interviewee.email) %></td>
    </tr>
  <% end %>
  </table>
  <% else %>
    <p>No upcoming interviews scheduled</p>
  <% end %>
  <h3>Recent</h3>

  
<%= link_to 'New Interview', new_interview_path %> 
</div>